import { Dish, Category } from '@/types/restaurant';

export const CATEGORIES = [
  'Салаты',
  'Супы', 
  'Горячие блюда',
  'Пицца',
  'Роллы',
  'Бургеры',
  'Десерты',
  'Напитки',
  'Закуски'
];

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Салаты', order: 1 },
  { id: '2', name: 'Супы', order: 2 },
  { id: '3', name: 'Горячие блюда', order: 3 },
  { id: '4', name: 'Пицца', order: 4 },
  { id: '5', name: 'Роллы', order: 5 },
  { id: '6', name: 'Бургеры', order: 6 },
  { id: '7', name: 'Десерты', order: 7 },
  { id: '8', name: 'Напитки', order: 8 },
  { id: '9', name: 'Закуски', order: 9 },
];

export const MOCK_DISHES: Dish[] = [
  {
    id: '1',
    name: 'Цезарь с курицей',
    description: 'Классический салат с курицей, пармезаном и соусом цезарь',
    price: 450,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
    category: 'Салаты',
    available: true,
    weight: '250г',
    ingredients: ['Куриная грудка', 'Салат романо', 'Пармезан', 'Соус цезарь', 'Сухарики'],
  },
  {
    id: '2',
    name: 'Греческий салат',
    description: 'Свежие овощи, фета, оливки и оливковое масло',
    price: 380,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
    category: 'Салаты',
    available: true,
    weight: '200г',
    ingredients: ['Помидоры', 'Огурцы', 'Сыр фета', 'Оливки', 'Красный лук', 'Оливковое масло'],
  },
  {
    id: '3',
    name: 'Борщ украинский',
    description: 'Традиционный борщ со сметаной и зеленью',
    price: 320,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400',
    category: 'Супы',
    available: true,
  },
  {
    id: '4',
    name: 'Солянка мясная',
    description: 'Сытный суп с мясом, колбасой и солеными огурцами',
    price: 380,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=400',
    category: 'Супы',
    available: true,
  },
  {
    id: '5',
    name: 'Стейк из говядины',
    description: 'Сочный стейк средней прожарки с гарниром',
    price: 890,
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400',
    category: 'Горячие блюда',
    available: true,
  },
  {
    id: '6',
    name: 'Паста карбонара',
    description: 'Классическая итальянская паста с беконом и сыром',
    price: 520,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400',
    category: 'Горячие блюда',
    available: true,
  },
  {
    id: '7',
    name: 'Тирамису',
    description: 'Нежный итальянский десерт с кофе и маскарпоне',
    price: 280,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
    category: 'Десерты',
    available: true,
  },
  {
    id: '8',
    name: 'Чизкейк нью-йорк',
    description: 'Классический американский чизкейк с ягодами',
    price: 320,
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400',
    category: 'Десерты',
    available: true,
  },
  {
    id: '9',
    name: 'Кофе американо',
    description: 'Классический черный кофе',
    price: 150,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400',
    category: 'Напитки',
    available: true,
  },
  {
    id: '10',
    name: 'Капучино',
    description: 'Кофе с молочной пенкой',
    price: 180,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400',
    category: 'Напитки',
    available: true,
  },
  {
    id: '11',
    name: 'Пицца Маргарита',
    description: 'Классическая пицца с томатами, моцареллой и базиликом',
    price: 650,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    category: 'Пицца',
    available: true,
    weight: '450г',
    ingredients: ['Тесто', 'Томатный соус', 'Моцарелла', 'Базилик', 'Оливковое масло'],
  },
  {
    id: '12',
    name: 'Пицца Пепперони',
    description: 'Пицца с острой колбасой пепперони и сыром',
    price: 720,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
    category: 'Пицца',
    available: true,
  },
  {
    id: '13',
    name: 'Филадельфия',
    description: 'Ролл с лососем, огурцом и сливочным сыром',
    price: 420,
    image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
    category: 'Роллы',
    available: true,
  },
  {
    id: '14',
    name: 'Калифорния',
    description: 'Ролл с крабом, авокадо и икрой тобико',
    price: 380,
    image: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=400',
    category: 'Роллы',
    available: true,
  },
  {
    id: '15',
    name: 'Чизбургер',
    description: 'Сочная котлета из говядины с сыром и овощами',
    price: 450,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    category: 'Бургеры',
    available: true,
    weight: '320г',
    ingredients: ['Булочка', 'Котлета говяжья', 'Сыр чеддер', 'Помидор', 'Салат', 'Соус'],
  },
  {
    id: '16',
    name: 'Бургер с беконом',
    description: 'Двойная котлета с беконом, сыром и соусом барбекю',
    price: 520,
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400',
    category: 'Бургеры',
    available: true,
  },
  {
    id: '17',
    name: 'Куриные крылышки',
    description: 'Острые куриные крылышки в соусе барбекю',
    price: 320,
    image: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400',
    category: 'Закуски',
    available: true,
  },
  {
    id: '18',
    name: 'Картофель фри',
    description: 'Хрустящий картофель фри с соусом',
    price: 180,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
    category: 'Закуски',
    available: true,
  },
];